### ISSUE TITLE
View chain sequences in Web GUI

### ISSUE THREAD

**Issue by ErikBjare** [Homebrain/Homebrain#10]
It doesn't have to be pretty, I just want something simple to get a basic overview of where agents send their events to.

**Comment by johan-bjareholt** [comment]
The configuration of agents in the WebUI is what I'm currently trying to solve, and this is part of that. That's the reason why i made it possible to see all installed modules in the WebUI this morning.

My plan is to first focus on making it possible to get  as much data about the agents and their connections as possible accessable from the WebUI, then afterwards try to come up with a good way to represent it.

I'm assigning myself to this, because it's my current focus.

**Comment by ErikBjare** [comment]
@johan-bjareholt Do you feel comfortable in Angular yet? Write it in whatever way works for you and then I can fix eventual parts that don't use Angular.

**Comment by johan-bjareholt** [comment]
@ErikBjare I'm fine with writing basic controllers, using scopes and fetching objects via rest, but aside from that I don't have much experience. So i know my way around how to use Angular fine, but I'm sure that there's alot of room for improvement to what i write, so feel free to rewrite and fix.

**Comment by johan-bjareholt** [comment]
Now it works, i had to do some tree generation and traversal, but it works.

Just shows a string of how the chains running.

**Comment by ErikBjare** [comment]
@johan-bjareholt Nice!

Closing this, if we want a more comprehensive system we'll do that when the need arises.
